export enum StudentActionTypes {
    GET_STUDENTS = 'GET_STUDENTS',
    GET_STUDENTS_SUCCESS = 'GET_STUDENTS_SUCCESS',
    GET_STUDENTS_ERROR = 'GET_STUDENTS_ERROR',
    GET_STUDENT = 'GET_STUDENT',
    GET_STUDENT_SUCCESS = 'GET_STUDENT_SUCCESS',
    ADD_STUDENT = 'ADD_STUDENT',
    ADD_STUDENT_SUCCESS = 'ADD_STUDENT_SUCCESS',
    DELETE_STUDENT = 'DELETE_STUDENT',
    DELETE_STUDENT_SUCCESS = 'DELETE_STUDENT_SUCCESS',
    UPDATE_STUDENT = 'UPDATE_STUDENT',
    UPDATE_STUDENT_SUCCESS = 'UPDATE_STUDENT_SUCCESS',
    GET_ALL_COURSES = 'GET_ALL_COURSES',
    GET_ALL_COURSES_SUCCESS = 'GET_ALL_COURSES_SUCCESS',
    UPDATE_STUDENT_COURSES = 'UPDATE_STUDENT_COURSES',
    UPDATE_STUDENT_COURSES_SUCCESS = 'UPDATE_STUDENT_COURSES_SUCCESS'
}